# Generated by Django 4.2.7 on 2023-11-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textrovertapp', '0002_textrovertappdata_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textrovertappdata',
            name='category',
            field=models.CharField(default='anger', max_length=200),
        ),
    ]
