# Generated by Django 4.2.7 on 2023-11-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textrovertapp', '0004_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
