# Generated by Django 4.2.7 on 2023-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textrovertapp', '0005_drink_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.AlterField(
            model_name='textrovertappdata',
            name='category',
            field=models.CharField(default='noemotion', max_length=200),
        ),
    ]
